### PR TITLE
nvcodec support

### PR DESCRIPTION
**Pull request by rsnk96**
Support for nvenc and nvdec for Nvidia GPU-Accelerated encoding and decoding.

Installs only if a valid version of CUDA is detected. Steps follow [this guide](https://developer.nvidia.com/ffmpeg) with the addition of the `sed` line to ensure that `sudo` permissions are not needed, and that it is a local copy.

### CODE REVIEW

**Comment by markus-perl** [comment]
Hi rsnk96, 

Thank you for your contribution. 

Normally I don't accept pull requests which require a preinstalled library to work. The basic idea of the script is that all dependencies are resolved automatically, without any user interaction.

But due to the size and hardware dependency of the Nvidia Cuda framework, we may need a different approach.

Possible solutions to include nvcodec in this script could be:
- Update the projects readme file with a short instruction or a link, what needs to be installed first to compile ffmpeg with nvcodec support
- Provide a build switch like --with-nvcodec and then download all required dependencies automatically.

Best,
Markus

**Comment by rsnk96** [comment]
I feel the first solution would be better, since having an extra build switch might make the script open to people installing `nv-codec` without having the dependencies installed. Will update the PR soon

**Comment by rsnk96** [comment]
Better now?

**Comment by rsnk96** [comment]
Hi @markus-perl 

Did you get a chance to review this?

**Comment by mliradelc** [comment]
Hi @rsnk96 I just used your PR, first of all great work! I made the same thing bat much more static than your approach 😃 .

Besides, I had to make some modifications to make it work:

- Add the latest change for master (Use C flags and LD flags from the workspace)
- Update FFmpeg source to the version 4.2.2


Another change I had to make to make it work it was to add a file with the env variables to `/etc/profile.d`, for example I put the name `nvidia.sh`

```bash
export PATH=/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2/NsightCompute-2019.5${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64 ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

It would be great to add a way to detect the version of the Cuda toolkit and the NsightCompute, with that, the Paths could be updated every time.

Here is my repo with the modifications (except the `nvidia.sh` file)
https://github.com/mliradelc/ffmpeg-build-script/tree/check-install-nvenc

**Comment by rsnk96** [comment]
Hi @mliradelc 

That's great! Please feel free to add on to this PR with your updates. Your repo seems to have quite a lot of good modifications and upgrades, perhaps Markus would want to split the upgrades into an independent PR, and have the `nvcodec` related upgrades in this PR (@markus-perl please let us know your opinion).

On updating the `PATH`, does Nsight Compute work with nvcodec only if ffmpeg is built while keeping it in its `PATH`? I have not used NsightCompute before, so just curious :)

**Comment by rsnk96** [comment]
My bad, just saw that the version upgrades was already merged into master.  The update looks good, please feel free to merge it into this PR @mliradelc  (you could send a PR to `https://github.com/detecttechnologies/ffmpeg-build-script/`. Once that is merged, this PR to `https://github.com/markus-perl/ffmpeg-build-script/` will automatically get updated).


Also, there is one small change you could consider:
> Use C flags and LD flags from the workspace

Perhaps the 
```bash
    --extra-cflags="-I$WORKSPACE/include" \
    --extra-ldflags="-L$WORKSPACE/lib" \
    --extra-cflags="$CFLAGS" \
    --extra-ldflags="$LDFLAGS" \
```

could be replaced by

```bash
    --extra-cflags="-I$WORKSPACE/include $CFLAGS" \
    --extra-ldflags="-L$WORKSPACE/lib $LDFLAGS" \
```

**Comment by mliradelc** [comment]
Hi @rsnk96 

Thank you for your kind words. I made like a year ago some modifications to build FFmpeg with nvenc, and the work of @markus-perl is the best that you can find on the internet over how to compile FFmpeg with almost all the codecs.

> It would be great to add a way to detect the version of the Cuda toolkit and the NsightCompute, with that, the Paths could be updated every time.

Well is true that the NsightCompute is not available when you install the Cuda drivers for FFmpeg. I left that command because it's stated in the installation of the Cuda drivers from Nvidia.

About the change, you suggested to me, I think is a good change and makes the code looks cleaner.

**Comment by rsnk96** [comment]
@mliradelc would you like to add your changes, or should I just update my PR..?

**Comment by mliradelc** [comment]
> @mliradelc would you like to add your changes, or should I just update my PR..?

Hi, I put a PR a few days ago https://github.com/detecttechnologies/ffmpeg-build-script/pull/1

**Comment by rsnk96** [comment]
> Hi, I put a PR a few days ago detecttechnologies#1

Sorry, saw that just now. Merged it!

@markus-perl this is up to date with master now. Two major upgrades are being done:
* `nvenc` support
* Using ffmpeg version tag `n4.2.2`

**Comment by markus-perl** [comment]
Thanks for the pull request. I will soon have a Linux test system here with an Nvidia graphics card, then I can test the pull request :-)

**Comment by markus-perl** [comment]
Guys, I'm sorry for the delay. I finally merged the pull request into the master branch. I was able to test the script on my ubuntu 20.04 box with an NVIDIA 1070 TI graphics card. Everything worked as expected.

**Pull request closed without merging**
