### PR TITLE
Enable 10-bit libx265 encodes

### PR DESCRIPTION
**Pull request by paladine**

### CODE REVIEW

**Comment by cdgriffith** [comment]
Good add, would be nice to also throw in `-DENABLE_HDR10_PLUS=ON`

  https://x265.readthedocs.io/en/master/releasenotes.html?highlight=ENABLE_HDR10_PLUS#id36

**Comment by rokibhasansagar** [comment]
Doesn't `-DHIGH_BIT_DEPTH=ON` only build the 10-bit version of x265 binary?

Right way to build multi-bit x265 binary is like this:
http://hg.videolan.org/x265/file/tip/build/linux/multilib.sh

**Comment by markus-perl** [comment]
Can someone post a command line example, how to encode such a video with 10-bit and how to verify that everything has worked with ffprobe?

**Comment by cdgriffith** [comment]
Example encodings:
```
/usr/bin/ffmpeg -y -i video.mp4 -map 0:v -c:v libx265 -pix_fmt yuv420p  -preset:v ultrafast   -map_metadata -1 -map_chapters -1 -an -sn -dn  "8bit.mp4"
/usr/bin/ffmpeg -y -i video.mp4 -map 0:v -c:v libx265 -pix_fmt yuv420p10le  -preset:v ultrafast   -map_metadata -1 -map_chapters -1 -an -sn -dn  "10bit.mp4"
/usr/bin/ffmpeg -y -i video.mp4 -map 0:v -c:v libx265 -pix_fmt yuv420p12le  -preset:v ultrafast   -map_metadata -1 -map_chapters -1 -an -sn -dn  "12bit.mp4"
```

Using the incorrectly configured build that only supports 10-bit, I will see a warning only on 12-bit, not 8-bit encodes:

```
Incompatible pixel format 'yuv420p12le' for codec 'libx265', auto-selecting format 'yuv420p10le'
```

But no error is ever raised, and the video converted. The help command (`/usr/bin/ffmpeg -hide_banner -h encoder=libx265`) will even list `yuv420p` as a supported pixel format. However, verifying with ffprobe shows they were all encoded at 10bit:

```
$ /usr/bin/ffprobe -hide_banner -show_entries stream=pix_fmt -print_format flat -loglevel panic 8bit.mp4
streams.stream.0.pix_fmt="yuv420p10le"

$ /usr/bin/ffprobe -hide_banner -show_entries stream=pix_fmt -print_format flat -loglevel panic 10bit.mp4
streams.stream.0.pix_fmt="yuv420p10le"

$ /usr/bin/ffprobe -hide_banner -show_entries stream=pix_fmt -print_format flat -loglevel panic 12bit.mp4
streams.stream.0.pix_fmt="yuv420p10le"
```

**Comment by cdgriffith** [comment]
Tried it myself but keep getting linking errors (don't do much hand compiling so might be something obvious) 

```bash
    download "https://bitbucket.org/multicoreware/x265_git/downloads/x265_3.5.tar.gz"
    rm -rf 8bit 10bit 12bit
    mkdir 8bit 10bit 12bit
    cd 12bit
    execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_CLI=OFF -DMAIN12=ON ../source
    execute make -j $MJOBS
    cd ../10bit
    execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DHIGH_BIT_DEPTH=ON -DEXPORT_C_API=OFF -DENABLE_CLI=OFF ../source
    execute make -j $MJOBS
    cd ../8bit
    execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DEXTRA_LIB="x265_main10.a;x265_main12.a" -DEXTRA_LINK_FLAGS=-L. -DLINKED_10BIT=ON -DLINKED_12BIT=ON ../source
    ln -sf ../10bit/libx265.a libx265_main10.a
    ln -sf ../12bit/libx265.a libx265_main12.a
    execute make -j $MJOBS

    mv libx265.a libx265_main.a

    if [[ "$OSTYPE" == "darwin"* ]]; then
      execute libtool -static -o libx265.a libx265_main.a libx265_main10.a libx265_main12.a 2>/dev/null
    else
      execute ar -M <<EOF
CREATE libx265.a
ADDLIB libx265_main.a
ADDLIB libx265_main10.a
ADDLIB libx265_main12.a
SAVE
END
EOF
    fi

    execute make install
```    

12 and 10 bit compile fine, then when linking the 8-bit start getting errors: 

```
[100%] Linking CXX executable x265
/usr/bin/ld: ./libx265_main10.a(api.cpp.o): in function `x265_10bit::x265_api_get_199(int)':
api.cpp:(.text+0x20b7): undefined reference to `dlopen'
/usr/bin/ld: api.cpp:(.text+0x20cb): undefined reference to `dlsym'
/usr/bin/ld: api.cpp:(.text+0x2125): undefined reference to `dlopen'
...
```

**Comment by rokibhasansagar** [comment]
> Good add, would be nice to also throw in `-DENABLE_HDR10_PLUS=ON`
> 
> [x265.readthedocs.io/en/master/releasenotes.html?highlight=ENABLE_HDR10_PLUS#id36](https://x265.readthedocs.io/en/master/releasenotes.html?highlight=ENABLE_HDR10_PLUS#id36)

Now that multi-bit x265 can be built successfully, maybe it's time to add HDR10_PLUS too.

BTW, does this feature work only in 10-bit encode? 😕

**Comment by cdgriffith** [comment]
> Now that multi-bit x265 can be built successfully, maybe it's time to add HDR10_PLUS too.
> 
> BTW, does this feature work only in 10-bit encode? 😕

Should be available in both 10 and 12 bit: example I've seen https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-x265.sh

I have a branch with it and new updates in https://github.com/cdgriffith/ffmpeg-build-script/blob/feature/x265/build-ffmpeg#L509

However the CUDA docker build cannot find x265 with pkg-config for some reason (All other builds including some tweaking to find libtool on macOS working) https://github.com/cdgriffith/ffmpeg-build-script/actions/runs/1223077271

**Comment by rokibhasansagar** [comment]
@cdgriffith Sir, Does the `libhdr10plus.a` library needs to be linked inside the unified `libx265.a` file before the `make install` step?

The multilib build script was made back in the 2015, but dynamicHDR was added later on somewhere around 2017 (I think). That's why the inclusion might not be added [there](http://hg.videolan.org/x265/file/tip/build/linux/multilib.sh).

I can't test the differences correctly, but I thought I'd let you know.

**Comment by cdgriffith** [comment]
@rokibhasansagar Probably doesn't need linked in EXTRA_LIBS even, as it works without that with BtnB's build scripts.

Going with what you suggest, I have tested  with adding it to the `ar` mixin as well and works fine (again except for with the cuda docker) 

I have a free/open HDR10+ test video https://github.com/cdgriffith/FastFlix/tree/master/tests/media and attached it's HDR10+ metadata json (also can just extract it from the video)  [metadata.json.zip](https://github.com/markus-perl/ffmpeg-build-script/files/7149677/metadata.json.zip)

Tested and recognized with MediaInfo



```
/usr/bin/ffmpeg -y -i "Beverly Hills Duck Pond - HDR10plus - Jessica Payne.mp4" -map 0:0 -c:v libx265 -pix_fmt yuv420p10le -x265-params "aq-mode=2:repeat-headers=1:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:hdr10_opt=1:master-display=G(7500,3000)B(34000,16000)R(13250,34500)WP(15635,16450)L(10000000,50):max-cll=1000,200:hdr10=1:chromaloc=0:dhdr10-info='metadata.json'" -crf:v 22 -preset:v superfast "Output.mkv"
```

**Comment by cdgriffith** [comment]
Figured out why the cuda build was failing. I switched to the official multicorewave repo (because hey, why not use the "real" one), also grabbing their 3.5 release. Turns out the videolan one currently being used in this script is actually 3.4 (look at x265Version.txt in the zip file) and there are code differences.  Switched back to the one that was being used originality. 

Updated on #106 

Tests passing on the branch run https://github.com/cdgriffith/ffmpeg-build-script/actions/runs/1227763031 (currently running on master which was just pushed)

**Comment by markus-perl** [comment]
Implemented with https://github.com/markus-perl/ffmpeg-build-script/pull/106

**Comment by rokibhasansagar** [comment]
> Figured out why the cuda build was failing. I switched to the official multicorewave repo (because hey, why not use the "real" one), also grabbing their 3.5 release. Turns out the videolan one currently being used in this script is actually 3.4 (look at x265Version.txt in the zip file) and there are code differences. Switched back to the one that was being used originality.

So, https://bitbucket.org/multicoreware/x265_git/commits/branch/Release_3.5 is the original v3.5 branch, which has 10 extra commits than videolan's git repo.

@cdgriffith sir, Does using this MCW's Release_3.5 branch breaking builds in CUDA jobs?

**Comment by cdgriffith** [comment]
@rokibhasansagar  correct, the pkg-config can't find it for some reason with that one https://github.com/cdgriffith/ffmpeg-build-script/actions/runs/1223077271

**Comment by rokibhasansagar** [comment]
> @rokibhasansagar correct, the pkg-config can't find it for some reason with that one [cdgriffith/ffmpeg-build-script/actions/runs/1223077271](https://github.com/cdgriffith/ffmpeg-build-script/actions/runs/1223077271)

@cdgriffith Sir, I added `git` in the build stage in `cuda-ubuntu.dockerfile`, and the build works with upstream MCW source.
https://github.com/rokibhasansagar/ffmpeg-build-script/runs/3675215324?check_suite_focus=true

In centos, we didn't see this error because git was pre-installed there.
And In full-static-docker build, x265 is omitted. So we don't see it there too.

**Pull request closed without merging**
