### PR TITLE
Numjobs

### PR DESCRIPTION
**Pull request by Mirabis**
Faster processing using variable job count.

### CODE REVIEW

**Comment by markus-perl** [comment]
Hi Mirabis, 
at least under Debian 7.8 and MacOSX 10.11 a syntax error is thrown:

$ ./build-ffmpeg
./build-ffmpeg: line 17: syntax error near unexpected token `elif'
./build-ffmpeg: line 17: `elif [ -f /proc/cpuinfo ]; then'

**Comment by Mirabis** [comment]
Ah hmm sorry, will check it out tomorrow - must be something with brackets and the " 's

**Comment by Mirabis** [comment]
Should be working now :)

Forgot the if.... and it started with elif somehow

**Comment by markus-perl** [comment]
Merged, thx for your work!

**Pull request merged**
